### ISSUE TITLE
代码开源吗？我想学习一下如何基于hysteria封装apk，谢谢大佬

### ISSUE THREAD

**Issue by kitty-eu-org** [lry127/Android-Hysteria-2-client#2]
代码开源吗？我想学习一下如何基于hysteria封装apk

**Comment by lry127** [comment]
这个apk是好久前封装的了，代码找不到了。不过我最近在基于Material 3重新开发。现在基本功能可以用，但是UI还没做完，所以你要在Android Studio里面改配置。新版本源码放到[release](https://github.com/lry127/Android-Hysteria-2-client/releases/tag/v2.5.1)了。

**Comment by lry127** [comment]
libhysteria.so是hysteria项目release直接下的，只是改了一个名字并在manifest里面声明了`extractNativeLibraries="true"`，这样这个可执行文件就被apk包中解压并释放到了文件系统里面，才能被Linux的Loader调起来。libtun2socks是用来实现vpn的，项目别人[开源](https://github.com/heiher/hev-socks5-tunnel)了。
![image](https://github.com/user-attachments/assets/3be662d2-be70-4d56-9481-663fe91c4a58)

**Comment by lry127** [comment]
你要是有对Jetpack Compose有兴趣的话后面我可以搞一个repo一起开发

**Comment by kitty-eu-org** [comment]
我在做一个跨平台的app里面涉及到安卓的，我是基于tauri-apps做的

**Comment by lry127** [comment]
那android原生部分也是不变的。主要是[VpnService](https://developer.android.com/reference/android/net/VpnService)里面注册linux的tun设备，拿到fd后启动tun2socks转发系统ip层流量到hysteria的socks端口。我没有tauri-apps的经验，但是release里面代码已经很简洁了，你可以参考下。

**Comment by kitty-eu-org** [comment]
好的，谢谢
