### ISSUE TITLE
hysteria2也有tun功能可以直接替代go-tun2socks吗？

### ISSUE THREAD

**Issue by sougouzhinan** [lry127/Android-Hysteria-2-client#3]

**Comment by lry127** [comment]
不可以，原生的只能在linux上用。自带的tun与android不兼容(android 的tun设备由系统统一管理， 而hysteria原生实现只能自己拿到linux的权限后创建tun设备，在android就得有root才可以)。

**Comment by lry127** [comment]
也许你可以hack一下hysteria的源码，让它接受一个tun设备的文件描述符然后启动tun的功能。见[VpnService](https://developer.android.com/reference/android/net/VpnService) 及 [VpnService.Builder#establish()](https://developer.android.com/reference/android/net/VpnService.Builder#establish())
